# Generated by Django 4.0.4 on 2022-05-27 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='arquivos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('data_transacoes', models.DateField(null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_transacoes'],
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_origem', models.CharField(max_length=30)),
                ('agencia_origem', models.CharField(max_length=10)),
                ('conta_origem', models.CharField(max_length=20)),
                ('banco_destino', models.CharField(max_length=30)),
                ('agencia_destino', models.CharField(max_length=10)),
                ('conta_destino', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_hora', models.DateTimeField()),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.arquivo')),
            ],
        ),
    ]
