# Generated by Django 4.0.4 on 2022-04-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='data_transacoes',
            field=models.DateField(null=True),
        ),
    ]
