# Generated by Django 4.0.4 on 2022-05-09 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transacao_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arquivo',
            old_name='criado_em',
            new_name='data_upload',
        ),
        migrations.RenameField(
            model_name='transacao',
            old_name='criado_em',
            new_name='data_upload',
        ),
        migrations.RemoveField(
            model_name='arquivo',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='atualizado_em',
        ),
    ]
