# Generated by Django 4.0.4 on 2022-04-18 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_arquivo_data_transacoes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivo',
            options={'ordering': ['-data_transacoes']},
        ),
        migrations.AlterModelOptions(
            name='transacao',
            options={},
        ),
    ]
